apiVersion: apps/v1
kind: Deployment
metadata:
  name: partybuilding-service
  namespace: party-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partybuilding-service
  template:
    metadata:
      labels:
        app: partybuilding-service
    spec:
      nodeSelector:
        ns: party-system
      containers:
      - name: partybuilding-service
        image: 192.168.4.126/yz-party/partybuilding-service:1.2.BUILD
        ports:
        - containerPort: 9300
        args:
          - --spring.datasource.username=root
          - --spring.datasource.password=123456
          - --mysql.ip=192.168.4.102
          - --mysql.port=8017
          - --spring.cloud.consul.host=consul.default
          - --spring.cloud.consul.port=8500
#          - --spring.redis.host=redis-h
#          - --spring.redis.port=26379
          - --spring.redis.sentinel.master=mymaster
          - --spring.redis.sentinel.nodes=redis-ha-announce-0:26379,redis-ha-announce-1:26379,redis-ha-announce-2:26379
          - --spring.redis.password=MTIzNDU2Cg==
          - --spring.rabbitmq.addresses=rabbitmq-ha:5672
          - --spring.rabbitmq.username=guest
          - --spring.rabbitmq.password=lTxFQHj7fvKHrMnseEhYzZAY

---
apiVersion: v1
kind: Service
metadata:
  name: partybuilding-service
  namespace: party-system
spec:
  type: NodePort
  selector:
    app: partybuilding-service
  ports:
  - protocol: TCP
    nodePort: 9300
    port: 9300
    targetPort: 9300
