
# 服务端口
server:
  port: 9300

spring:
  application:
    # 应用名称
    name: partybuilding-service
  # 环境
  profiles:
    active: dev
  # sleuth链路追踪
  sleuth:
    web:
      client:
        enabled: true
    # 采样比率 1.0 全部需要
    sampler:
      probability: 1.0
  # rabbitmq配置
  rabbitmq:
    addresses: 192.168.5.251:5672
    username: Yizheng
    password: Yizheng2017
  # redis
  redis:
    host: 192.168.5.251
  cloud:
    # consul
    consul:
      host: localhost
      port: 10025
      discovery:
        enabled: true
        register: true
        heartbeat:
          enabled: true
          ttl-unit: s
          ttl-value: 30
        prefer-ip-address: true
        tags:
        - partybuilding

# mybatis-plus
mybatis-plus:
  # mapper文件地址
  mapper-locations:
  - classpath*:mapping/*/*.xml
  - classpath:mapping/*.xml
  # 类型别名包路径
  type-aliases-package: com.yizheng.commons.domain,com.yizheng.partybuilding.system.entity,com.yizheng.partybuilding.entity,com.yizheng.partybuilding.dto,com.yizheng.partybuilding.system.dto
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    # 逻辑删除字段
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# feign
feign:
  hystrix:
    enabled: true
  # 使用okhttp
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  # 压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true

# hystrix 与FeignTokenInerceptor配合
hystrix:
  command:
    default:
      execution:
        isolation:
          # 隔离策略
          strategy: SEMAPHORE
          thread:
            # 超时时间
            timeoutInMilliseconds: 6000
  shareSecurityContext: true


# 请求处理的超时时间
ribbon:
  # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 1
  # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false
  # 超时配置
  ReadTimeout: 1500
  ConnectTimeout: 1500

# 日志级别
logging:
  level:
    root: warn
    com.yizheng.partybuilding: info
    com.yizheng.partybuilding.repository : debug
    com.yizheng.partybuilding.system.mapper : debug

# 自定义配置

# 定义jwt token的过期时间，单位是分钟
com:
  jwttoken:
    expireTime: 600
  word:
    generatorPath: D:\\
  #文件上传服务地址
  upload:
    path: http://dev.egov-china.com:9007/api/upload
    authorization: Basic dXBsb2FkZXI6dXBsb2FkZXI=

# swagger
swagger:
  apiinfo:
    title: 党组织、党员、生活活动相关API

# mysql 地址配置
mysql:
  ip: 192.168.4.102
  port: 8017