
spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: party
    password:  3bf9d1f7f0e13723a6ff
    url: jdbc:mysql://119.23.215.202:8017/partbuilding?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000